
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://le4ker.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

#baseurl: /lazarocosta

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "John Smith"
title: "Lázaro Costa"
description: "Blog and website of John Smith, blogging mainly for tech. Opinions expressed are mine."
keywords: "smith, jones, personal, jekyll, theme"
favicon: "../img/lazaro.jpg"

################
# Header layout #
################

black-favicon: ""
logo: "../img/lazaro.jpg" # leave blank if you don't want a logo

background-img: "../img/FEUP-background.jpg"

##############################
# Dynamic Text on the Header #
##############################
dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "The secret to success is knowing something that no one else knows [Aristóteles]."
# - text: "Where’s your will to be weird?"

me-img: "/img/lazaro.jpg"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/user_name.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: false
fb-share: False
twitter-share: False
linkedin-share: False
reddit-share: False
google-plus-share: False
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

disqus-shortname: "personal-jekyll-theme"

syntax-highlight: True


#################
# Projects #
############
collections:
 publications:
    sort_by: year
    permalink: /publications/:year/:month/:day/:title:output_ext
 projects:
    sort_by: year
    permalink: /projects/:year/:month/:day/:title:output_ext
 organizations:
   sort_by: year
   permalink: /organizations/:year/:month/:day/:title:output_ext


############
# Timeline #
############

events:
  - image: "/img/timeline/MasterDegree.png"
    date: "July 2019"
    description: "Completed my Master’s degree in Informatics Engineering at Faculty of Engineering at University of Porto (FEUP)"
  - image: "/img/timeline/FEUP.png"
    date: "September 2019 - Today"
    description: "Invited Assistant Professor at FEUP"
  - image: "/img/timeline/INESCTEC.png"
    date: "October 2019 - May 2020"
    description: "Full-Stack Developer (www.inesctec.pt/en/projects/ icon)"
  - image: "/img/timeline/INESCTEC.png"
    date: "May 2020 - September 2021"
    description: "Full-Stack Developer (www.inesctec.pt/pt/projetos/episa)"
  - image: "/img/timeline/phdStudent.jpg"
    date: "September 2021 - Today"
    description: "PhD student at FEUP"

# First image of the Timeline

timeline-img: "/img/lazaro.jpg"

###########
# Contact #
###########

email: "lazaro@fe.up.pt"


# Set a url pointing to your publish PGP Public Key here, and it will appear in the Contact section
pgp: False

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
#author_blurb: "John Smith is an awesome person. He lives in Flatland, where he works on two-dimensional engineering projects. In his spare time, John likes to eat cotton candy."
#author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://www.facebook.com/lazaro.costa.00"
  - title: "github"
    url: "https://github.com/lazarocosta"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: johnsmith
keybase-in-social: false
keybase-in-footer: True

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  #Blog: 'latest-post'
  Projects: 'projects'
  Publications: 'publications'
  Organizations: 'organizations'
  Work experience: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"


# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
